TesterApp-MVC5/University/Models/Entities/Alumni.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using University.Models.Enums;

namespace University.Models.Entities
{
    public class Alumni: Person
    {
        [Display(Name = "Graduation Year")]
        public int GraduationYear { get; set; }

        public Alumni ()
        {
            Type = PersonType.Alumni.ToString();
        }
    }
}

TesterApp-MVC5/University/Models/Entities/Lecturer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using University.Models.Enums;

namespace University.Models.Entities
{
    public class Lecturer: Person
    {
        [StringLength(50)]
        public string Subject { get; set; }

        public Lecturer()
        {
            Type = PersonType.Lecturer.ToString();
        }
    }
}

TesterApp-MVC5/University/Models/Entities/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using University.Models.Enums;

namespace University.Models.Entities
{
    public class Person
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        [Required]
        [StringLength(50)]
        public string Type { get; set; }

        public static Type SelectFor(PersonType type)
        {
            switch (type)
            {
                case PersonType.Student:
                    return typeof(Student);
                case PersonType.Alumni:
                    return typeof(Alumni);
                case PersonType.Lecturer:
                    return typeof(Lecturer);
                default:
                    throw new Exception();
            }
        }
    }
}

TesterApp-MVC5/University/Models/Entities/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using University.Models.Enums;

namespace University.Models.Entities
{
    public class Student: Person
    {
        [StringLength(50)]
        public string Faculty { get; set; }

        public Student()
        {
            Type = PersonType.Student.ToString();
        }
    }
}

TesterApp-MVC5/University/Models/Enums/PersonType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace University.Models.Enums
{
  public enum PersonType
    {
        Student,
        Alumni,
        Lecturer
    }
}

TesterApp-MVC5/University/Models/PersonModelBinder.cs
/*
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using University.Models.Entities;
using University.Models.Enums;

namespace University.Models
{ 
    public class PersonModelBinder: DefaultModelBinder
    {
        protected override object CreateModel(ControllerContext controllerContext, ModelBindingContext bindingContext, Type modelType)
        {
            PersonType personType = GetValue<PersonType>(bindingContext, "PersonType");

            Type model = Person.SelectFor(personType);

            Person instance = (Person)base.CreateModel(controllerContext, bindingContext, model);

            bindingContext.ModelMetadata = ModelMetadataProviders.Current.GetMetadataForType(() => instance, model);

            return instance;
        }

        private T GetValue<T>(ModelBindingContext bindingContext, string key)
        {
            ValueProviderResult valueResult = bindingContext.ValueProvider.GetValue(key);

            bindingContext.ModelState.SetModelValue(key, valueResult);

            return (T)valueResult.ConvertTo(typeof(T));
        }
    }
}*/

TesterApp-MVC5/University/Models/ViewModels/PersonData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using University.Models.Entities;

namespace University.Models.ViewModels
{
    public class PersonData
    {
        public Person Person { get; set; }
        public Alumni Alumni { get; set; }
        public Student Student { get; set; }
        public Lecturer Lecturer { get; set; }
    }
}

TesterApp-MVC5/University/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace University.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TesterApp-MVC5/University/Controllers/PeopleController.cs
using System.Net;
using System.Web;
using System.Web.Mvc;
using University.Models.Entities;
using University.Models.Enums;
using University.Models.ViewModels;
using University.Services;

namespace University.Controllers
{
    public class PeopleController : Controller
    {
        private readonly UniversityManager _universityManager = new UniversityManager();

        public ActionResult Index(string searchString="", int searchType=0)
        {

            var people = _universityManager.GetPeopleByCriteria(searchString, searchType);
            
            return View(people);

        }

        public ActionResult Details(int? id, PersonType type)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var person = _universityManager.GetPersonDetailsByTypeAndId(id.Value, type);

            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,PhoneNumber,Email")] Person person)
        {
            if (ModelState.IsValid)
            {
                var result = _universityManager.CreateNewPerson(person);

                if (result)
                    RedirectToAction("Index");
            }
            
            return View(person);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var person = _universityManager.GetPersonById(id);

            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(PersonData person)
        {
            if (ModelState.IsValid)
            {
                var res = _universityManager.UpdatePersonDetails(person);
                if (res)
                 return RedirectToAction("Index");
            }
            return View(person);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var person = _universityManager.GetPersonById(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _universityManager.DeletePersonById(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _universityManager.DisposeDB();
            }
            base.Dispose(disposing);
        }
    }
}

TesterApp-MVC5/University/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TesterApp-MVC5/University/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TesterApp-MVC5/University/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TesterApp-MVC5/University/Views/People/Create.cshtml
@model University.Models.Entities.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesterApp-MVC5/University/Views/People/Delete.cshtml
@model University.Models.Entities.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TesterApp-MVC5/University/Views/People/Details.cshtml
@model University.Models.ViewModels.PersonData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Type)
        </dd>

        @if (Model.Alumni != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Alumni.GraduationYear)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Alumni.GraduationYear)
            </dd>
        }

        @if (Model.Lecturer != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Lecturer.Subject)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lecturer.Subject)
            </dd>
        }

        @if (Model.Student != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Student.Faculty)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Student.Faculty)
            </dd>
        }



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Person.ID, type = Model.Person.Type }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TesterApp-MVC5/University/Views/People/Edit.cshtml
@model University.Models.Entities.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesterApp-MVC5/University/Views/People/Index.cshtml
@model List<University.Models.Entities.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Create New", "Create")

@using (Html.BeginForm())
{
    <p>
        Search For: @Html.TextBox("SearchString") 
        By  : @Html.DropDownList("SearchType", new List<SelectListItem>

                 {
                    new SelectListItem{ Text="First Name", Value = "1" },
                    new SelectListItem{ Text="Last Name", Value = "2" }
                 }) 
        <input class="btn" type="submit" value="Search" />
    </p>
}

@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Phone Number
            </th>
            <th>
                Email
            </th>
            <th>
                Type
            </th>
            <th></th>
        </tr>

        @if (Model != null && Model.Count() > 0)
        {
            for (int i = 0; i < Model.Count(); i++)
            {
                <tr>

                    <td>
                        <input type="hidden" name="Index" value="@i" />
                        @Html.DisplayFor(e => e[i].FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(e => e[i].LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(e => e[i].PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(e => e[i].Email)
                    </td>
                    <td>
                        @Html.DisplayFor(e => e[i].Type)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = Model[i].ID, type = Model[i].Type }) |
                        @Html.ActionLink("Details", "Details", new { id = Model[i].ID, type = Model[i].Type }) |
                        <a onclick="Delete(@Model.ToList()[i].ID)">Delete</a>

                    </td>
                </tr>
            }

        }

    </table>
}

TesterApp-MVC5/University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="Scripts/App/site.js" type="text/javascript"></script> 

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("University App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("University","Index","People")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET University App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>